### ISSUE TITLE
缺少了文件，造成无法编译通过

### ISSUE THREAD

**Issue by Angry-Rabbit** [HeskeyBaozi/dva-blog-crud-demo#1]
Error in ./src/routes/UserPage/UserPage.jsx
Module not found: ../../assets/genji.jpg
Module not found: ../../assets/hanzo.jpg

**Comment by HeskeyBaozi** [comment]
感谢你的问题
这两个文件是用户的头像图片
genji是源氏（普通用户
hanzo是半藏（管理员
现在已更新。不会报错了
